FROM gcc:14
RUN apt-get update && \
    apt-get install -y \
    cmake \
    make \
    git \
    wget \
    unzip \
    build-essential \
    libssl-dev \
    && rm -rf /var/lib/apt/lists/*
WORKDIR /workspace
CMD ["/bin/bash"]

FROM gcc:14
RUN apt-get update && \
    apt-get install -y \
    cmake \
    make \
    git \
    wget \
    unzip \
    build-essential \
    libssl-dev \
    && rm -rf /var/lib/apt/lists/*
WORKDIR /workspace
CMD ["/bin/bash"]
